### ISSUE TITLE
Does this shader support all the android phones?

### ISSUE THREAD

**Issue by Nagarajvasu** [keijiro/ProcAmp#1]
This shader not working on Lenovo k3 note and Nexus 5. I had blue mat video to remove blue surface i am using your shader. Its works fine with Google pixel phone but it doesn't work with above mentioned mobile phones. thanks for using your stuff.

**Comment by keijiro** [comment]
I think there is something wrong with the shader. Could you send a log (logcat) of them? It might contain some shader compilation error messages.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen if you have further issues.
